services:
  lan-chat:
    container_name: lan-chat
    restart: always
    network_mode: host
    build: http://100.103.115.101:8888/lan-chat.tar.gz
    volumes:
      - /vol1/1000/docker/lan-chat/data:/app/data
    environment:
      - LAN_CHAT_ADMIN=admin
      - LAN_CHAT_ADMIN_PASSWORD=admin123
