services:
  lan-chat:
    container_name: lan-chat
    restart: always
    network_mode: host
    image: ghcr.io/ivamullane-bot/lan-chat:latest
    volumes:
      - /vol1/1000/docker/lan-chat/data:/app/data
    environment:
      - LAN_CHAT_ADMIN=admin
      - LAN_CHAT_ADMIN_PASSWORD=admin123
